# Practice day 11.5

1. Create 1D, 2D, 3D arrays and print dimensions + shapes

In [2]:
import numpy as np
# 1D
arr1 = np.array([1, 2, 3])
print(arr1.ndim, arr1.shape)

# 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.ndim, arr2.shape)

# 3D
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3.ndim, arr3.shape)

1 (3,)
2 (2, 3)
3 (2, 2, 2)


2)  Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7


In [3]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 5))
filled_arr = np.full((3, 3), 7)

print(zeros_arr)
print(ones_arr)
print(filled_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


Create an array of even numbers between 10 and 50 using arange.


In [4]:
even_nums = np.arange(10, 51, 2)
print(even_nums)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 4×4 matrix from 0–15. Then , extract:
the first row


the last column


a 2×2 subarray from the center


In [5]:
mat = np.arange(16).reshape(4, 4)
print(mat)

first_row = mat[0]
last_col = mat[:, -1]
center_2x2 = mat[1:3, 1:3]

print(first_row)
print(last_col)
print(center_2x2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 3  7 11 15]
[[ 5  6]
 [ 9 10]]


 Add a 1D array [1,2,3] to each row of a 3×3 matrix.


In [6]:
matrix = np.arange(9).reshape(3, 3)
add_arr = np.array([1, 2, 3])

result = matrix + add_arr
print(result)


[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


Given two arrays A and B, compute:
(A + B) / 2


A**2 + B**2


In [7]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

part1 = (A + B) / 2
part2 = A**2 + B**2

print(part1)
print(part2)


[2.5 3.5 4.5]
[17 29 45]
