<a href="https://colab.research.google.com/github/Dipta3567/AI_ML/blob/main/python_basic/Data_Analysis_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is numerical python  
Core structure -> nd array  

Numpy -->
 1) Linear Algebra
 2) Math
 3) Statistic
 4) Mathmatical  



In [82]:
# Without numpy
arr = [1,2,3]
print( arr *5)

arr =[ x*5 for x in arr]

print (arr)


[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [83]:
# using numpy
import numpy as np

arr1= np.array([1,2,3])

arr1= arr1*5

print (arr1)

[ 5 10 15]


#NDarray



1d array

In [84]:
arr1 = np.array([1,2,3,4,5])

print(type(arr1))
print(arr1.ndim) # array dimension check

<class 'numpy.ndarray'>
1


2d Array

In [85]:
arr2 = np.array([
                  [1,2,3], # row 1
                  [4,5,6]  # row 2
                ])

print(arr2.ndim)

2


3d Array

In [86]:
arr3 = np.array([
    # 1st floor

      [
           [1,2,3],
           [4,5,6]
      ],

      # 2nd floor

      [
           [7,8,9],
           [10,11,12]
      ],
    # 3rd floor
      [
           [13, 14, 15],
           [16, 17, 18]
      ]
    # there can be many floor
])

print(arr3.ndim)

3


#Array attributes

Dimension

In [87]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


Shape

In [88]:
print(arr1.shape) # it will show colum
print(arr2.shape) # it will show row and coloum
print(arr3.shape) # it will show floor, row, coloum

(5,)
(2, 3)
(3, 2, 3)


Data type

In [89]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


Size

In [90]:
print(arr1.size) # it will show total item
print(arr2.size)
print(arr3.size)

5
6
18


#NDarray data type

By Default use upcasting method to decide dtype

In [91]:
arr = np.array([1,2,3])
print (arr.dtype)


arr = np.array([1.5,2.4,3.2])
print(arr.dtype)

int64
float64


Upcasted to float

In [92]:
arr = np.array([1, 2, 3.2]) # ata int na dhore float dorse
print(arr.dtype)

float64


Upcasted to string

In [93]:
arr = np.array([1 ,2.4, "3.2"])
print(arr.dtype)

<U32


# Selecting a data type for an array

In [94]:
arr = np.array([1, 2, 3], dtype=np.int8) # int 8 e -127 to +128 porjonto rakte parbo er beshi rakle error dibe
print(arr.dtype)


arr = np.array([1, 2,300])
print(arr.dtype)
arr = arr.astype(np.float128)
print(arr.dtype)



int8
int64
float128


# NDarray creating from existing data

List

In [95]:
lst = [10, 20, 30, 40, 50.6]

arr = np.array(lst)
print("\nLIST : \n")
print(arr)
print(type(arr))
print(arr.dtype)

arr = np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)


Mix_lst = [10, True, "Hello", 10.5]

arr = np.array(Mix_lst)
print(arr)
print(type(arr))
print(arr.dtype)


LIST : 

[10.  20.  30.  40.  50.6]
<class 'numpy.ndarray'>
float64
[10 20 30 40 50]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32


Matrix

In [96]:
matrix= [
    [1, 2, 3],
    [4, 5, 6]
]
print("\nMatrix : \n")
arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


Matrix : 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


tupple

In [97]:
tpl =(10, 20, 30)
arr = np.array(tpl)
print("\nTupple : \n")
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


Tupple : 

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1


Set

In [98]:
st={1, 2, 3}
print("\nSET : \n")
arr = np.array(st)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

st={1, 2, 3}
print("\nSET : \n")
arr = np.array(list(st))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


SET : 

{1, 2, 3}
<class 'numpy.ndarray'>
object
()
0

SET : 

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


Dictionary

In [99]:
dc = {'a' : 10, 'b' : 20, 'c' : 30}
print("\nDictionary : \n")
print(type(dc))
print(dc.keys())
key = dc.keys()
print(key)
print(dc.values())
print(dc.items())


Dictionary : 

<class 'dict'>
dict_keys(['a', 'b', 'c'])
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


keys to ndarry

In [100]:
arr = np.array(list(dc.keys()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


values to ndarry

In [101]:
arr = np.array(list(dc.values()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3


Items to ndarray

In [102]:
arr = np.array(list(dc.items()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# NDarray creation from scratch

np.zero use for creating array

In [103]:
arr = np.zeros((1,3)) # 1 ta row and 3 colum
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[0. 0. 0.]]
<class 'numpy.ndarray'>
float64
(1, 3)
2
3




kono array er moto array nite cayle

In [104]:
arr = np.zeros_like(arr3) # arr3 used in up as 3d array
print(arr)
print(arr.shape)
print("\n")

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)




np.ones

In [105]:
arr = np.ones((1,3)) # 1 ta row and 3 colum
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")


arr = np.ones((3,4,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

arr = np.ones_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[1. 1. 1.]]
<class 'numpy.ndarray'>
float64
(1, 3)
2
3


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
float64
(3, 4, 3)
3
36


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int64
(3, 2, 3)
3
18




np.empty use random value

In [106]:
arr = np.empty((4,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

arr = np.empty_like(arr3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[9.88e-324 4.94e-324 9.88e-324]
 [4.94e-324 3.95e-323 4.94e-324]
 [1.43e-322 1.43e-322 1.38e-322]
 [1.09e-322 9.88e-323 1.14e-322]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int64
(3, 2, 3)
3
18




np.full

In [107]:
arr = np.full((4,3),10) # every value will be set to 10
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

arr = np.full((4,3),True)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

arr = np.full((4,3),np.inf)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

arr = np.full_like(arr3,27)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
bool
(4, 3)
2
12


[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12


[[[27 27 27]
  [27 27 27]]

 [[27 27 27]
  [27 27 27]]

 [[27 27 27]
  [27 27 27]]]
<class 'numpy.ndarray'>
int64
(3, 2, 3)
3
18




# ndarray generation with random values

np.ramdom.rand(shape)

In [108]:
arr = np.random.rand(2,3) # the value will be between 0 to 1 and uniform style the value distribute kore

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[0.6498749  0.0152283  0.84110902]
 [0.37403442 0.63747387 0.6287639 ]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6




int value jonno

In [109]:
arr = np.random.randint(1, 10, (2,3)) # first 2 digit holo koto theke koto modhe value and then size. and 1d lagle size e colum na dile hobe and row the colum hishabe kaj korbe
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[1 2 7]
 [6 7 7]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
6




float value jonno

In [110]:
arr = np.random.uniform(1, 10, (2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[8.7236984  4.12741726 8.46249939]
 [4.917523   9.26851873 7.38834529]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6




# ndarray creation from range

np.arange(first, end, step)

In [111]:
arr = np.arange(1, 10, 1)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
(9,)
1
9




jodi matrix lage then

In [112]:
arr = np.arange(1, 10, 1).reshape(3,3)
# or
mat = arr.reshape(3,3)
print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9




np.linspace(start, end, point) akane point bolte akta distance ke same pariman  divide korbe

In [113]:
arr = np.linspace(1, 10, 10)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>
float64
(10,)
1
10




np.logspace( start, end, koita) ata power based distance.

In [114]:
arr = np.logspace(0, 15, 6)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[1.e+00 1.e+03 1.e+06 1.e+09 1.e+12 1.e+15]
<class 'numpy.ndarray'>
float64
(6,)
1
6




jodi power e base change lage

In [115]:
arr = np.logspace(0, 4, 6 , base = 2)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print("\n")

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
<class 'numpy.ndarray'>
float64
(6,)
1
6




# creating diagonal and identity matrix for linear algebra

Diagonal Matrix

In [116]:
diagonal_mat = np.diag([1,2,3,4])
print(diagonal_mat)
print(diagonal_mat.shape)
print("\n")

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)




Identity Matrix

In [117]:
identity_mat= np.eye(3)
print(identity_mat)
print(identity_mat.shape)
print("\n")

identity_mat= np.eye(3, 4) # row and colum
print(identity_mat)
print(identity_mat.shape)
print("\n")

identity_mat= np.eye(3,4,-1) # -1 mane diagonal 1 row down hoi jabe. 1 dile upore utbe
print(identity_mat)
print(identity_mat.shape)
print("\n")


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
(3, 4)


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
(3, 4)




# ndarray Indexing and Slicing

##indexing

In [118]:
print(arr1)
print("\n")
print(arr2)
print("\n")

print(arr1[2])
print("\n")
arr1[2]= 100
print(arr1[2])
print(arr1)
print("\n")
print(arr2[1][2])
arr2[1][2]= 95
print(arr2[1][2])

[1 2 3 4 5]


[[1 2 3]
 [4 5 6]]


3


100
[  1   2 100   4   5]


6
95


##Slicing

1d array = arr[start:end:step]

In [119]:
arr1_mod=arr1[1:4]
print(arr1_mod)
print("\n")

[  2 100   4]




###2d = arr[row_start : row_end , column_start : column_end : step]

In [120]:
print(arr2)
print("\n")

row_0=arr2[0:1 ,] # ata 0 row ne and colum by default pura tai ne
print(row_0)
print("\n")

row_1=arr2[1:,]
print(row_1)
print("\n")

[[ 1  2  3]
 [ 4  5 95]]


[[1 2 3]]


[[ 4  5 95]]




Column

In [121]:
col_0=arr2[:,0:1]
print(col_0)
print("\n")

col_0=arr2[:,1:2]
print(col_0)
print("\n")

[[1]
 [4]]


[[2]
 [5]]




getting a protion

In [122]:
portion = arr2[:,0:2]
print(portion)
print("\n")

[[1 2]
 [4 5]]




# Ndarray Copy Advanced Indexing and Iteration

slicing er khetre mod ta real er sathe link thake ty mod e change korle real e change hoi

In [123]:
print(arr1)
print("\n")
print(arr1_mod)
arr1_mod[0]=5
print(arr1)
print("\n")
print(arr1_mod)

[  1   2 100   4   5]


[  2 100   4]
[  1   5 100   4   5]


[  5 100   4]


but copy funtion use korle normal thakbe

In [124]:
arr1_mod=arr1[1:4].copy()
print(arr1)
print("\n")
print(arr1_mod)

arr1_mod[2]=200
print(arr1)
print("\n")
print(arr1_mod)

[  1   5 100   4   5]


[  5 100   4]
[  1   5 100   4   5]


[  5 100 200]


Advanced indexing

In [125]:
lst = np.array([10, 20, 30, 40])

values = lst[[1,3]] # ata just index er value return kore not range
print(values)

print("\n")

print(arr2)

print("\n")
print(arr2[[0,1], [1,2]]) # lets print 2 and 95

[20 40]


[[ 1  2  3]
 [ 4  5 95]]


[ 2 95]


boolean

In [126]:
print(arr2[arr2>2]) # print greater then value 2

arr2[arr2>2]=0
print(arr2)

[ 3  4  5 95]
[[1 2 0]
 [0 0 0]]


iteration

In [127]:
arr = np.array([[10,20,30], [40, 50, 60]])
for i in np.nditer(arr): # we can also use for 3d or more
  print(i)

10
20
30
40
50
60


# ndarray Manipulation -1

In [128]:
arr = np.random.randint(1,100, size=(10,5)) # ex: sample : 10 and feature : 5
print(arr)

arr.shape
print("\n")

[[27 70 85 51 66]
 [93 35 44 35 83]
 [13 60 95 83 32]
 [34 42 50 33 84]
 [48 57 30 25 54]
 [56 64 45 56 11]
 [43 36 64 72 47]
 [12  6 22 37 88]
 [62 51 72 28 26]
 [20 89 28 56 30]]




change row and colum

In [129]:
b=arr.reshape(5,10) # 5*10 = 50. jodi bole 3*5 = 15 mani data loss ja invalid. ty size choto kora jabe na
# kintu 25*2 or 2*25 kora jabe karon eder data  = 50
print(b)
b.shape

b.ndim

print("\n")

[[27 70 85 51 66 93 35 44 35 83]
 [13 60 95 83 32 34 42 50 33 84]
 [48 57 30 25 54 56 64 45 56 11]
 [43 36 64 72 47 12  6 22 37 88]
 [62 51 72 28 26 20 89 28 56 30]]




data ke 1d te convert

In [130]:
# flatten

flat= b.flatten() # ata row wise pasha pashi add kore 1d kore
print(flat)
print("\n")

[27 70 85 51 66 93 35 44 35 83 13 60 95 83 32 34 42 50 33 84 48 57 30 25
 54 56 64 45 56 11 43 36 64 72 47 12  6 22 37 88 62 51 72 28 26 20 89 28
 56 30]




colum base pashi pashi boshai 1d jonno

In [131]:
column_flat=np.ravel(b, order='F')
print(column_flat)
print("\n")

column_flat=np.ravel(b, order='C')
print(column_flat)
print("\n\n")

[27 13 48 43 62 70 60 57 36 51 85 95 30 64 72 51 83 25 72 28 66 32 54 47
 26 93 34 56 12 20 35 42 64  6 89 44 50 45 22 28 35 33 56 37 56 83 84 11
 88 30]


[27 70 85 51 66 93 35 44 35 83 13 60 95 83 32 34 42 50 33 84 48 57 30 25
 54 56 64 45 56 11 43 36 64 72 47 12  6 22 37 88 62 51 72 28 26 20 89 28
 56 30]





 | Option | Meaning                                           | Flattening order                                           |
 | :----- | :------------------------------------------------ | :--------------------------------------------------------- |
 | `'C'`  | **C order** (row-major, default)                  | Row by row (left → right, top → bottom)                    |
 | `'F'`  | **Fortran order** (column-major)                  | Column by column (top → bottom, left → right)              |
 | `'A'`  | **Any order** (depends on memory layout of array) | Uses row-major if array is C-contiguous, else column-major |
 | `'K'`  | **Keep order**                                    | Follows the actual memory layout (most “raw” form)         |


concrate 2 array

In [132]:
a=np.random.randint(1, 10, size=(2,3))
b=np.random.randint(20, 30, size=(2,3))

print(a,b)
print("\n")

[[1 4 4]
 [9 8 1]] [[28 29 26]
 [21 27 28]]




row wise concrate korar shomoi 2 ta array er colum same thakte hobe

In [133]:
con = np.concatenate((a,b),axis=0)
print(con)
print("\n")

[[ 1  4  4]
 [ 9  8  1]
 [28 29 26]
 [21 27 28]]




column wise concrate korar shomoi 2 ta array er row same thakte hobe

In [134]:
con = np.concatenate((a,b), axis=1)
print(con)

[[ 1  4  4 28 29 26]
 [ 9  8  1 21 27 28]]


Error

In [135]:
#x=np.random.randint(1, 10, size=(2,3))
#y=np.random.randint(20, 30, size=(1,3))

#con = np.concatenate((x,y),axis=0)
#print(con)
#print("\n")

#con = np.concatenate((x,y), axis=1)
#print(con)

# ndarray Manipulation - 2

Transpose

In [136]:
mat = np.array([[10,20,30],
                [30,40,50]
                ])
transpose = mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


Array Split

In [137]:
a = np.random.randint(1, 10, size= (10,))
print(a)
splited_array = np.array_split(a,3) # akane jodi shudu split use kori tahole error dibe karon split equal bhabe divide kore but akane size 10 ty equal hobe na
print(splited_array)

[8 3 9 8 4 7 2 1 7 4]
[array([8, 3, 9, 8]), array([4, 7, 2]), array([1, 7, 4])]


# ndarray Arithmetic Operators and Mathematical function

In [138]:
x = [10, 20,30, 40]
y=[2, 3, 4, 5]

Add , Sub, Mul, Div, Remainder

In [139]:
add =x+y
print(add)

x = np.array([10, 20,30, 400])
y=np.array([2, 3, 4, 5])
add = x+y # or np.add(x,y)
print(add)

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x%y
print(remainder)

[10, 20, 30, 40, 2, 3, 4, 5]
[ 12  23  34 405]
[  8  17  26 395]
[  20   60  120 2000]
[ 5.          6.66666667  7.5        80.        ]
[0 2 2 0]


Trigonomatry

In [140]:
# sin, cos, tan takes values in radian
sin_val = np.sin(x)
print(sin_val)

print(np.cos(x))

[-0.54402111  0.91294525 -0.98803162 -0.85091936]
[-0.83907153  0.40808206  0.15425145 -0.52529634]


Radian to degree

In [141]:
deg=np.rad2deg(x)
print(deg)

[  572.95779513  1145.91559026  1718.87338539 22918.31180523]


deg to rad

In [142]:
print(np.deg2rad(x))

[0.17453293 0.34906585 0.52359878 6.98131701]


Log


In [143]:
# log 10 mane kono digit ke 10 diye koibar bhag kora jabe like 100/10 = 10 this is 1 time and then 10/10=1. its 2nd time

base_10_log_val = np.log10(x)
print(base_10_log_val)
two_diye_bhag = np.log2(x)
print(two_diye_bhag)

[1.         1.30103    1.47712125 2.60205999]
[3.32192809 4.32192809 4.9068906  8.64385619]


Sqrt

In [144]:
sqrt=np.sqrt(x)
print(sqrt)

[ 3.16227766  4.47213595  5.47722558 20.        ]


different

In [145]:
print(np.sum(x))
cuml=np.cumsum(x)
print(cuml)

460
[ 10  30  60 460]


# Numpy Broadcasting

square the hole array

In [146]:
x = np.array ([10, 8, 16, 100])

result = x **2 #

print(result)

[  100    64   256 10000]


In [147]:
mat = np.array([[10,20,30],
                [40,50,60]])

result = mat+2
print(result)
print("\n")

vector = np.array([1,2,3]) # akane jodi 1,2,3,4 ni tahole error ashbe karon akane colum num same hoyte hobe
result = vector+mat
print(result)

[[12 22 32]
 [42 52 62]]


[[11 22 33]
 [41 52 63]]


# Numpy Logical Functions

Comparison : >, <, >=, <=, ==, !=

In [148]:
x =np.array([10, 8, 16, 100])
y=np.array([2, 3, 4, 5])
print(x >y)
print(x==y)

[ True  True  True  True]
[False False False False]


all() shob true kina check

In [149]:
print(np.all(x>y))
print(np.all(x==y))
print(np.all(y))

True
False
True


any() akane jekono akta true ase kina

In [150]:
print(np.any(x==y))
print(np.any(x>y))
print(np.any(x))

False
True
True


# ndarray Sorting

inplace

In [151]:
x = np.array([10, 8, 16, 2, 100])

z= x.copy()

print(z)
z.sort()
print(z)

print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16   2 100]
[  2   8  10  16 100]
[ 10   8  16   2 100]
[  2   8  10  16 100]
[ 10   8  16   2 100]


2d array sorting

In [152]:
mat= np.array([[10, 3, 5], [8, 4, 9]])

# horizon sorting

hor_sort = np.sort(mat, axis=1)
print(hor_sort)

# vertical

ver_sort = np.sort(mat, axis=0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# ndarray Searching

In [153]:
x = np.array([10, 8, 16, 2, 100])
# we will check if x has 16 and which index

# np.where (condition, x, y) if true x , otherwise replace with y

index = np.where(x==16)
print(index)

index = np.where(x>8) # this return index
print(index)

array = np.where(x>8 , x, 0) # this returns array
print(index)

(array([2]),)
(array([0, 2, 4]),)
(array([0, 2, 4]),)


In [154]:

# 2d

mat= np.array([[10, 3, 5], [8, 4, 9]])

index = np.where(mat > 8)
print(index) # it will return 1st x axis then y axis

arr = np.where(mat > 8, mat, 0)
print(arr)


# counting
maximum_val_index= np.argmax(x)
print(x)
print(maximum_val_index)

minimum_val_index= np.argmin(x)
print(minimum_val_index)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]
[ 10   8  16   2 100]
4
3


# ndarray Counting


In [155]:
a = np.random.randint(1, 100, size=(100,))
print(a)

[96 22  6 74 25 57 32 84 99 36 91 48 35 94 96 81 17 69 91 48 42 54 86 82
 14 66 87 36 78 99 17 29 89 27 36 94 37 16 49 93 94 96  2  3  4 51 68 93
 34 99 90 75  6 91 81  1 19 40 58 33 86 54 40 91 90 76 31 63 62 27 74  7
  3 97 43  8 19  8 32  1 97 65 86 94 92 63 39 10 74 99 84 86 19 78 65 56
 78 99 64 25]


In [156]:
value_great_than_60 = np.count_nonzero(a>60)
print(value_great_than_60)
val = np.count_nonzero(a==29)
print(val)

51
1


###Unique value koita check

In [157]:
uni= np.unique(a)
print(uni)


[ 1  2  3  4  6  7  8 10 14 16 17 19 22 25 27 29 31 32 33 34 35 36 37 39
 40 42 43 48 49 51 54 56 57 58 62 63 64 65 66 68 69 74 75 76 78 81 82 84
 86 87 89 90 91 92 93 94 96 97 99]


unique value koita koto bar ase check

In [158]:
uni,cnt= np.unique(a, return_counts=True)
print(uni)
print("\n")
print(cnt)

[ 1  2  3  4  6  7  8 10 14 16 17 19 22 25 27 29 31 32 33 34 35 36 37 39
 40 42 43 48 49 51 54 56 57 58 62 63 64 65 66 68 69 74 75 76 78 81 82 84
 86 87 89 90 91 92 93 94 96 97 99]


[2 1 2 1 2 1 2 1 1 1 2 3 1 2 2 1 1 2 1 1 1 3 1 1 2 1 1 2 1 1 2 1 1 1 1 2 1
 2 1 1 1 3 1 1 3 2 1 2 4 1 1 2 4 1 2 4 3 2 5]


# Statistical function

Student score  csv file upload

In [81]:
from google.colab import files
uploaded = files.upload()


Saving student_scores.csv to student_scores.csv


Read the data

In [159]:
data = np.genfromtxt('/content/student_scores.csv', delimiter=',', skip_header=1) # skip_header=1 for skiping header
print(data)



[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


Math marks slice or 1st colum show only

In [160]:
math_marks = data[::,:1] # row wise default raksi and colum wise 1
print(math_marks)

print("\n")
# row style dekayte hole
print(math_marks.T)

print(np.max(math_marks))

print(np.min(math_marks))

print(np.mean(math_marks)) # For avarage

median = np.median(math_marks) # it means mordhom
print(median)

[[78.]
 [56.]
 [89.]
 [45.]
 [70.]
 [92.]
 [61.]
 [55.]
 [88.]
 [74.]
 [66.]
 [80.]
 [59.]
 [73.]
 [91.]
 [68.]
 [77.]
 [84.]
 [62.]
 [95.]]


[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5


Standard Deviation means if the marks are closer to average or scatter

In [161]:
std_math_marks = np.std(math_marks)
print(std_math_marks) # atar man beshi hole mani scatter


13.788672887555204


# Linear Algebra with NumPy

In [162]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([32, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

Corelation means one value affect another value. here increse of study hours affects in increase in scores of exam

In [163]:
corelation = np.corrcoef(data)
print("Correlation Matrix : \n", corelation)

Correlation Matrix : 
 [[1.         0.90909647]
 [0.90909647 1.        ]]


Dot product

In [164]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

B= np.array([
    [7,8],
    [9,10],
    [11,12]
])

# a er colum and b er row same hote hobe
dot_product = np.dot(A,B)
print(dot_product)



[[ 58  64]
 [139 154]]


Diagonal er sum ke trace bole

In [165]:
print(np.trace(B)) # it sum up the 10+7 in b matrix

17


Determinant conditon is it has to be a square matrix means same row and colum

In [166]:
sq_mat= np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(sq_mat.shape)

det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

(3, 3)
-4.263256414560599e-12


rank

In [167]:
rank_sq= np.linalg.matrix_rank(sq_mat)
print(rank_sq)

2


# Problem Solving

https://www.deep-ml.com/problems/4

In [168]:
import numpy as np

def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:

	mat =np.array(matrix)

	if mode =="row":
		x=1
	else:
		x=0

	means = np.mean(matrix,axis=x)


	return means

https://www.deep-ml.com/problems/1

In [169]:
import numpy as np

def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.

    a = np.array(a)
    b=np.array(b)

    shape_a = a.shape
    if shape_a[1]!=b.size:
        return -1

    dot = np.dot(a,b).tolist()
    return dot



# Practice day 11.5

1. Create 1D, 2D, 3D arrays and print dimensions + shapes

In [170]:
# 1D
arr1 = np.array([1, 2, 3])
print(arr1.ndim, arr1.shape)

# 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.ndim, arr2.shape)

# 3D
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3.ndim, arr3.shape)

1 (3,)
2 (2, 3)
3 (2, 2, 2)


2)  Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7


In [171]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 5))
filled_arr = np.full((3, 3), 7)

print(zeros_arr)
print(ones_arr)
print(filled_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


Create an array of even numbers between 10 and 50 using arange.


In [172]:
even_nums = np.arange(10, 51, 2)
print(even_nums)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create a 4×4 matrix from 0–15. Then , extract:
the first row


the last column


a 2×2 subarray from the center


In [173]:
mat = np.arange(16).reshape(4, 4)
print(mat)

first_row = mat[0]
last_col = mat[:, -1]
center_2x2 = mat[1:3, 1:3]

print(first_row)
print(last_col)
print(center_2x2)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 3  7 11 15]
[[ 5  6]
 [ 9 10]]


 Add a 1D array [1,2,3] to each row of a 3×3 matrix.


In [174]:
matrix = np.arange(9).reshape(3, 3)
add_arr = np.array([1, 2, 3])

result = matrix + add_arr
print(result)


[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


Given two arrays A and B, compute:
(A + B) / 2


A**2 + B**2


In [176]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

part1 = (A + B) / 2
part2 = A**2 + B**2

print(part1)
print(part2)


[2.5 3.5 4.5]
[17 29 45]
